name: personal_flow
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Verificar esses
  # google_sign_in: ^4.0.7
  # flutter_facebook_login: ^3.0.0
  # file: ^5.0.10
  # async_loader: ^0.1.2
  #

  expandable: ^3.0.0+1
  path_provider: ^1.3.0
  pull_to_refresh: ^1.5.6
  flutter_slidable: ^0.5.3
  flutter_inner_drawer: ^0.4.0
  curved_navigation_bar: ^0.3.1
  draggable_flutter_list: ^1.0.3
  primary_secondary_progress_bar: ^0.1.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/fundo.png
  uses-material-design: true































