name: personalflow
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in:
  firebase_auth:
  flutter_launcher_icons:
  flutter_slidable:
  firebase_core:
  cloud_firestore:
  dio:
  flutter_mobx:
  mobx:
  flutter_modular:
  flutter_animation_progress_bar:
  eva_icons_flutter:

dev_dependencies:
  mockito:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "logo_app"
  ios: true
  image_path: "assets/icons/logo_app.png"

flutter:
  uses-material-design: true

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
