name: personalflow
description: A new Flutter application.

version: 1.0.0+1

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    google_sign_in: ^4.4.4
    firebase_auth: ^0.16.0
    flutter_launcher_icons: ^0.7.5
    flutter_slidable: ^0.5.4
    firebase_core: ^0.4.4+3
    cloud_firestore: ^0.13.5
    dio: ^3.0.9
    flutter_mobx: ^1.1.0
    mobx: ^1.1.1
    flutter_modular: ^1.1.2
    flutter_animation_progress_bar: ^1.0.0
    eva_icons_flutter: ^2.0.0

dev_dependencies:
    mockito: ^4.1.1
    mobx_codegen: ^1.0.3
    build_runner: ^1.9.0
    flutter_test:
        sdk: flutter

flutter_icons:
    android: "logo_app"
    ios: true
    image_path: "assets/icons/logo_app.png"

flutter:
    uses-material-design: true

scripts:
    mobx: flutter pub run build_runner watch --delete-conflicting-outputs
